parameters:
#    morgz_queue.example.class: Morgz\Bundle\QueueBundle\Example

services:
#    morgz_queue.example:
#        class: %morgz_queue.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
